### PR TITLE
Victor

### PR DESCRIPTION
**Pull request by VictorOmotor**
Please review. They are working as it should. Endpoints are on Postman.
The rest of the functionalities have been provided as well and the routes have been trimmed.

### CODE REVIEW

**Comment by Iupac120** [comment]
okay bro

**Comment by Iupac120** [comment]
I will review it tomorrow. i need light

**Review by Iupac120 — CHANGES_REQUESTED** [review]
Nice. But the cart, order and coupon should be the one I worked on. Thanks

**Comment by VictorOmotor** [comment]
* I have included every other thing that the developers would need, including storing the accessTokens in the database and clearing the cookies properly on logout, as was noted by Jide on Slack. The developers will have to reach out to you for the cart, order and payment functionalities. 
*  You did not have to create a request to main while this one is still pending. Please do well to approve this merge request and then replace the cart, order, and payment routes the way you deem fit. 
* When you are done, and you are sure the routes are working fine, please merge it at once without requestinf for approval because I may not have the chance to review it or even understand anything.
* When you are done with everything on staging, please ensure you let me know so that I can deploy the App on render to run on staging branch, as it is temporarily running on my branch. I can always do that with my phone anytime.
* The coming week will be very tasking for me and I urge that you please step in to continue in the communication with the frontend guys when the need arises.
* Here is the link to the hosted App on netlify: https://64a9621901213a7f6d786959--sweet-sherbet-b3e0da.netlify.app/
* Do well to review and send your reviews to Angela Raphael. 
* Cheers!

**Comment by Iupac120** [comment]
No problem.
Happy Sunday.

**Comment by Iupac120** [comment]
okay.

**Review by Iupac120 — APPROVED** [review]
Nice work.

**Review by Iupac120 — APPROVED** [review]

**Review by Iupac120 — APPROVED** [review]

**Pull request merged**
